services:
  server:
    image: go-server:latest
    ports:
       - "8080:8080"
    # image: nginx:latest
    # ports:
    #   - "80:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
    #   - app